apiVersion: v1
kind: ConfigMap
metadata:
  name: fatura-config
data:
  SERVER_PORT: "3333"
  APPLICATION_NAME: fatura
  DATABASE_URL: jdbc:postgresql://host.docker.internal:5432/fatura
  DATABASE_DRIVER: org.postgresql.Driver
  DATABASE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
  DDL_STRATEGY: update
  KAFKA_GROUPID: fatura
  KAFKA_TOPICS: transacoes
  KAFKA_BOOTSTRAP_SERVER: http://host.docker.internal:9092
  JWT_ISSUER: http://host.docker.internal:18080/auth/realms/nosso-cartao
  JWT_JWKSET: http://host.docker.internal:18080/auth/realms/nosso-cartao/protocol/openid-connect/certs
  JAEGER_URL: http://host.docker.internal:14268/api/traces
  VAULT_HOST: host.docker.internal
  HOST_CARTOES: http://host.docker.internal:8888