apiVersion: v1
kind: Service
metadata:
  labels:
    app: fatura
  name: fatura
spec:
  ports:
    - name: http
      port: 3333
      protocol: TCP
      targetPort: 3333
  type: LoadBalancer
  selector:
    app: fatura